export const nutrientIds = {
    base: {
        cals:               1,
        carbs:              2,
        chol:               3,
        fats:               4,
        fiber:              5,
        protein:            6,
        sodium:             7,
        sugar:              8,
        saturatedFat:       17,
        transFat:           18,
        polyunsaturatedFat: 19,
        monounsaturatedFat: 20,
        omega3:             21,
        addedSugar:         22,
        dietaryFiber:       23,
    },
    vitamins: {
        a:              9,
        b12:            10,
        c:              11,
        d:              12,
        thiamin:        24,
        niacin:         25,
        pantothenicAcid:26,
        b6:             27,
        biotin:         28,
        folate:         29,
        e:              30,
        k:              31,
    },
    minerals: {
        calcium:   13,
        iron:      14,
        magnesium: 15,
        potassium: 16,
        zinc:      32,
        selenium:  33,
        phosphorus:34,
        manganese: 35,
        iodine:    36,
        copper:    37,
    },
} as const;

export const nutrientDvArray = [
    nutrientIds.base.carbs,
    nutrientIds.base.chol,
    nutrientIds.base.fiber,
    nutrientIds.base.protein,
    nutrientIds.base.sodium,
    nutrientIds.base.saturatedFat,
    nutrientIds.base.addedSugar,

    nutrientIds.vitamins.a,
    nutrientIds.vitamins.thiamin,
    nutrientIds.vitamins.niacin,
    nutrientIds.vitamins.pantothenicAcid,
    nutrientIds.vitamins.b6,
    nutrientIds.vitamins.biotin,
    nutrientIds.vitamins.folate,
    nutrientIds.vitamins.b12,
    nutrientIds.vitamins.c,
    nutrientIds.vitamins.d,
    nutrientIds.vitamins.e,
    nutrientIds.vitamins.k,

    nutrientIds.minerals.calcium,
    nutrientIds.minerals.iron,
    nutrientIds.minerals.magnesium,
    nutrientIds.minerals.potassium,
    nutrientIds.minerals.zinc,
    nutrientIds.minerals.selenium,
    nutrientIds.minerals.phosphorus,
    nutrientIds.minerals.manganese,
    nutrientIds.minerals.iodine,
    nutrientIds.minerals.copper,
] as const;
